
   ############################################################
   ##                                                        ##
   ##                       APPAREILS                        ##
   ##                                                        ##
   ############################################################

- platform: template
  sensors:

    rm4mini_template:
      friendly_name: 'RM4 mini'
      value_template: "{{ 'on' if is_state('device_tracker.routeuryop_rm4_31_f9_30', 'home') else 'off' }}"
      icon_template: "{{ 'mdi:remote' if is_state('device_tracker.routeuryop_rm4_31_f9_30', 'home') else 'mdi:power' }}"
      
    lama_template:
      friendly_name: 'LAMA'
      value_template: "{{ 'on' if is_state('device_tracker.routeuryop_lama_1', 'home') else 'off' }}"
      icon_template: "{{ 'mdi:sever' if is_state('device_tracker.routeuryop_lama_1', 'home') else 'mdi:power' }}"   
      
    domoyop_template:
      friendly_name: 'DomoYop'
      value_template: "{{ 'on' if is_state('device_tracker.routeuryop_domoyop', 'home') else 'off' }}"
      icon_template: "{{ 'mdi:alpha-z-circle' if is_state('device_tracker.routeuryop_domoyop', 'home') else 'mdi:power' }}"   

    serveur_vm_template:
      friendly_name: 'Serveur VM'
      value_template: "{{ 'on' if is_state('device_tracker.routeuryop_hp_g8_1', 'home') else 'off' }}"
      icon_template: "{{ 'mdi:ubuntu' if is_state('device_tracker.routeuryop_hp_g8_1', 'home') else 'mdi:power' }}"   
