################################################################
###   Calcul debit net - methode basée sur les données SNMP  ###
################################################################

# For monitoring traffic on interfaces I'm using next oids :
# .1.3.6.1.2.1.2.2.1.2.2 value : eth0
# .1.3.6.1.2.1.2.2.1.2.3 value : eth1
# .1.3.6.1.2.1.2.2.1.2.5 value : eth2
# .1.3.6.1.2.1.2.2.1.2.6 value : eth3
# .1.3.6.1.2.1.2.2.1.2.7 value : eth4
#
# for bytes in:
# .1.3.6.1.2.1.31.1.1.1.6.2 value : eth0
# .1.3.6.1.2.1.31.1.1.1.6.3 value : eth1
# .1.3.6.1.2.1.31.1.1.1.6.5 value : eth2
# .1.3.6.1.2.1.31.1.1.1.6.6 value : eth3
# .1.3.6.1.2.1.31.1.1.1.6.7 value : eth4
#
# for bytes out:
# .1.3.6.1.2.1.31.1.1.1.10.2 value : eth0
# .1.3.6.1.2.1.31.1.1.1.10.3 value : eth1
# .1.3.6.1.2.1.31.1.1.1.10.5 value : eth2
# .1.3.6.1.2.1.31.1.1.1.10.6 value : eth3
# .1.3.6.1.2.1.31.1.1.1.10.7 value : eth4
#
# For monitoring cpu load I'm using:
#
# .1.3.6.1.2.1.25.3.3.1.2.196608 value : cpu0
# .1.3.6.1.2.1.25.3.3.1.2.196609 value : cpu1

# autre methode
#  https://community.home-assistant.io/t/snmp-bandwidth-monitor/7122
# sensor:
#   - platform: snmp
#     name: 'ER lite WAN In'
#     host: 192.168.194.1
#     baseoid: 1.3.6.1.2.1.31.1.1.1.6.2
#     community: 'erlmonitor'
#     version: '2c'
#     scan_interval: 10

#   - platform: derivative
#     source: sensor.er_lite_wan_in
#     unit_time: s
#     unit: B
#     name: erl_wan_in_derivative

#   - platform: template
#     sensors:
#       erl_wan_in_mbps:
#         value_template:  "{{ ((states('sensor.erl_wan_in_derivative')|float*8)/1000000)|round(2) }}"
#         unit_of_measurement: 'Mbps'
#         entity_id: sensor.erl_wan_in_derivative
#         friendly_name: Internet in Dev

#  methode issue de
#  https://community.home-assistant.io/t/snmp-bandwidth-monitor-using-statistics/96684/4
# eth0 LAN
sensor:
  - platform: snmp
    name: "ERL LAN In Bytes"
    host: 192.168.194.1
    baseoid: 1.3.6.1.2.1.31.1.1.1.6.2
    community: "erlmonitor"
    version: "2c"
    scan_interval: 10
    unit_of_measurement: Bytes
  - platform: snmp
    name: "ERL LAN Out Bytes"
    host: 192.168.194.1
    baseoid: 1.3.6.1.2.1.31.1.1.1.10.2
    community: "erlmonitor"
    version: "2c"
    scan_interval: 10
    unit_of_measurement: Bytes
  - platform: template
    sensors:
      erl_lan_in_mb:
        value_template: "{{ (states('sensor.erl_lan_in_bytes')|float*8/1000000)|round(2) }}"
        unit_of_measurement: 'Mb'
        # entity_id: sensor.erl_lan_in_mb #deprecated?
      erl_lan_out_mb:
        value_template: "{{ (states('sensor.erl_wan_out_bytes')|float*8/1000000)|round(2) }}"
        unit_of_measurement: 'Mb'
        # entity_id: sensor.erl_wan_out_mb #deprecated?
  - platform: statistics
    name: "ERL LAN In MBps"
    entity_id: sensor.erl_lan_in_mb
    state_characteristic: change_second
    # sampling_size: 4
    max_age:
      # hours: 24
      minutes: 1
  - platform: statistics
    name: "ERL LAN Out MBps"
    entity_id: sensor.erl_lan_out_mb
    state_characteristic: change_second
    # sampling_size: 4
    max_age:
      # hours: 24
      minutes: 1
    # Stats change !!!!!
    # https://github.com/home-assistant/core/pull/59867
  # - platform: statistics
  #   name: 'ERL LAN In Stats'
  #   entity_id: sensor.erl_lan_in
  #   state_characteristic: mean
  #   sampling_size: 4
  #   max_age:
  #     hours: 24
  # - platform: statistics
  #   name: 'ERL LAN Out Stats'
  #   entity_id: sensor.erl_lan_out
  #   state_characteristic: mean
  #   sampling_size: 4
  #   max_age:
  #     hours: 24
  # - platform: template
  #   sensors:
  #     erl_lan_in_mbps:
  #       value_template: "{{ (state_attr('sensor.erl_lan_in_stats','change_rate')|float*8*(state_attr('sensor.erl_lan_in_stats', 'sampling_size')-1)/1000000)|round(2) }}"
  #       unit_of_measurement: 'MBps'
  #       entity_id: sensor.erl_lan_in_mbps
  #     erl_lan_out_mbps:
  #       value_template: "{{ (state_attr('sensor.erl_lan_out_stats','change_rate')|float*8*(state_attr('sensor.erl_lan_out_stats', 'sampling_size')-1)/1000000)|round(2) }}"
  #       unit_of_measurement: 'MBps'
  #       entity_id: sensor.erl_lan_out_mbps
  # eth1 WAN
  - platform: snmp
    name: "ERL WAN In Bytes"
    host: 192.168.194.1
    baseoid: 1.3.6.1.2.1.31.1.1.1.6.3
    community: "erlmonitor"
    version: "2c"
    scan_interval: 10 #10
    unit_of_measurement: Bytes
  - platform: snmp
    name: "ERL WAN Out Bytes"
    host: 192.168.194.1
    baseoid: 1.3.6.1.2.1.31.1.1.1.10.3
    community: "erlmonitor"
    version: "2c"
    scan_interval: 10 #10
    unit_of_measurement: Bytes
  - platform: template
    sensors:
      erl_wan_in_mb:
        value_template: "{{ (states('sensor.erl_wan_in_bytes')|float*8/1000000)|round(2) }}"
        unit_of_measurement: 'Mb'
        # name: "ERL WAN In MBytes"
        # entity_id: sensor.erl_wan_in_mb #deprecated?
      erl_wan_out_mb:
        value_template: "{{ (states('sensor.erl_wan_out_bytes')|float*8/1000000)|round(2) }}"
        unit_of_measurement: 'Mb'
        # name: "ERL WAN Out MBytes"
        # entity_id: sensor.erl_wan_out_mb #deprecated?
      erl_wan_in_kb:
        value_template: "{{ (states('sensor.erl_wan_in_bytes')|float*8/1000)|round(3) }}"
        unit_of_measurement: 'Kb'
        # entity_id: sensor.erl_wan_in_kb #deprecated?
      erl_wan_out_kb:
        value_template: "{{ (states('sensor.erl_wan_out_bytes')|float*8/1000)|round(3) }}"
        unit_of_measurement: 'Kb'
        # entity_id: sensor.erl_wan_out_kb #deprecated?
  - platform: statistics
    name: "ERL WAN In Kbps"
    entity_id: sensor.erl_wan_in_kb
    state_characteristic: change_second
    sampling_size: 4
    max_age:
      hours: 24
  - platform: statistics
    name: "ERL WAN Out Kbps"
    entity_id: sensor.erl_wan_out_kb
    state_characteristic: change_second
    sampling_size: 4
    max_age:
      hours: 24
  - platform: statistics
    name: "ERL WAN In Mbps"
    entity_id: sensor.erl_wan_in_mb
    state_characteristic: change_second
    sampling_size: 4
    max_age:
      hours: 24
  - platform: statistics
    name: "ERL WAN Out Mbps"
    entity_id: sensor.erl_wan_out_mb
    state_characteristic: change_second
    sampling_size: 4
    max_age:
      hours: 24

  # - platform: statistics
  #   name: 'ERL WAN in Stats'
  #   entity_id: sensor.erl_wan_in
  #   sampling_size: 4
  #   max_age:
  #     hours: 24
  # - platform: statistics
  #   name: 'ERL WAN out Stats'
  #   entity_id: sensor.erl_wan_out
  #   sampling_size: 4
  #   max_age:
  #     hours: 24
  # - platform: template
  #   sensors:
  #     erl_wan_in_mbps:
  #       value_template: "{{ (state_attr('sensor.erl_wan_in_stats','change_rate')|float*8*(state_attr('sensor.erl_wan_in_stats', 'sampling_size')-1)/1000000)|round(2) }}"
  #       unit_of_measurement: 'MBps'
  #       entity_id: sensor.erl_wan_in_mbps
  #     erl_wan_out_mbps:
  #       value_template: "{{ (state_attr('sensor.erl_wan_out_stats','change_rate')|float*8*(state_attr('sensor.erl_wan_out_stats', 'sampling_size')-1)/1000000)|round(2) }}"
  #       unit_of_measurement: 'MBps'
  #       entity_id: sensor.erl_wan_out_mbps
